Added full screen mode
JavaCafe01/PdfViewer pull request #116
Opened 2021-03-13 13:15 UTC by CodeAssemblingChicken

Regarding #18 
I added a button to toggle full screen mode. Right now it is located in the bottom control menu, but feel free to move the toggle wherever you please.
Full screen mode hides StatusBar, NavigationBar and ActionBar.

2021-03-13 14:12 UTC, JavaCafe01 requested changes
Hey! Thanks for this PR. It seems Travis failed and I've pointed out why. After it passes, I'll test it out on my device.

2021-03-13 14:12 UTC, JavaCafe01 commented on app/src/main/res/menu/fab_menu.xml
> +        android:title="@string/fullscreen"
Wrong identifier, should be full_screen. this is why the travis build failed

2021-03-13 14:53 UTC, CodeAssemblingChicken commented
Now that was stupid of me (lesson learnt: always check code after changing spelling)
Hopefully, the PR updated after the new commit?

2021-03-14 00:00 UTC, JavaCafe01 approved these changes

2021-03-27 11:07 UTC, Fs00 reviewed
This is very nice and welcome change @CodeAssemblingChicken!
I find a couple of small things that could be changed to make your code a bit more consistent with what's already in place (it should take you no more than 10 mins).

2021-03-27 11:07 UTC, Fs00 commented on app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
> +        final View view = findViewById(R.id.pdfView);
Instead of using `findViewById` (which is the old-school way, nothing intrinsically wrong with it), you should use `viewBinding.pdfView` at line 325 and 332 to avoid an unnecessary lookup of the view (see https://developer.android.com/topic/libraries/view-binding if you want to learn more about it).

2021-03-27 11:52 UTC, CodeAssemblingChicken commented on app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
> +        final View view = findViewById(R.id.pdfView);
Thank you for the feedback!
Not removing `final Window w = getWindow();` was an unnecessary oversight from when I tested different things. Good thing it's gone now 😃
I don't usually code for Android, so it is always nice to learn something new as with View Bindings. Thanks for the hint.

2021-04-14 19:59 UTC, Fs00 approved these changes
@JavaCafe01 This is ready to be merged. Could you merge this and review my other PR when you have some time?

2021-04-24 09:53 UTC, merged