Spanish translation
JavaCafe01/PdfViewer pull request #61
Opened 2020-10-09 21:05 UTC by salvadorrueda

Hi. Spanish translation is ready to merge. I also fixed some minor issues with values in "untranslatable" entries. 

Let me know if everything is ok. Have fun.

2020-10-10 08:36 UTC, salvadorrueda commented
Ups. What happened?

2020-10-30 04:46 UTC, elJoa requested changes
Hey! I found some errors in the translation. I think I left some so let me know! :D

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="toast_pick_file_error">Imposible acceder al fichero. Comprueba el estado del gestor de ficheros.</string>
```suggestion
    <string name="toast_pick_file_error">Fue imposible abrir el fichero. Comprueba el estado del gestor de ficheros.</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="toast_http_code_error">"Problema cargando página, http error code : "</string>
```suggestion
    <string name="toast_http_code_error">"Ocurrió un problema cargando la página, código de error HTTP: "</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="intro">Repetir Intro</string>
```suggestion
    <string name="intro">Repetir intro</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="description_open">Por supuesto esta es una aplicación de código abierto. Tienes la opción de hacer tus própias modificaciones. El enlace al código fuente está en la sección About. A
```suggestion
    <string name="description_open">Por supuesto esta es una aplicación de código abierto. Tienes la opción de hacer tus propias modificaciones. El enlace al código fuente está en la sección Acerca de.</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="notice">Buenas notícias. Pdf Viewer Plus está disponible en F-Droid!</string>
```suggestion
    <string name="notice">Buenas notícias. ¡Pdf Viewer Plus está disponible en F-Droid!</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="password">Password</string>
```suggestion
    <string name="password">Contraseña</string>
```

2020-10-30 04:46 UTC, elJoa commented on app/src/main/res/values-es-rES/strings.xml
> +    <string name="reload_sum">Para poder aplicar los cambios, el PDF debe ser volver a abrir.</string>
```suggestion
    <string name="reload_sum">Para poder aplicar los cambios, el PDF se debe volver a abrir.</string>
```

2021-01-19 09:33 UTC, JavaCafe01 commented
Hello @elJoa and @salvadorrueda , I believe there are some updated strings, can you all take a look and update the translations? Please take a look in the dev branch and target the dev branch. Thanks!

2021-01-19 13:43 UTC, elJoa commented
Sure, I'll take a look when I get to home.

2021-01-21 14:20 UTC, elJoa commented
Ok, I have all strings translated. Should I open a separate pull request since I can't upload them here?

2021-02-21 13:20 UTC, JavaCafe01 commented
#90 merged

2021-02-21 13:20 UTC, closed without merging