Added italian translation
JavaCafe01/PdfViewer pull request #64
Opened 2020-10-10 21:40 UTC by Pyr0x1

Hi, hope this italian translation can be useful. If it will be merged, can you please mark the PR with the `hacktoberfest-accepted` label?

2020-11-30 14:00 UTC, Fs00 requested changes
I've pointed out some errors and things that can be improved in your translation.
Other than those, I would highly recommend you not to use title-style capitalization (e.g. Apri **File**) in any of the strings. This is a convention used sometimes in English but not in Italian (not in professional, high quality translations at least).
Therefore I would ask you to use capital letters only when needed (e.g. at the beginning of the string).

2021-01-19 09:34 UTC, JavaCafe01 commented
Hello @Pyr0x1, I believe there are some updated strings, can you take a look and update the translations? Please take a look in the dev branch and target the dev branch. Thanks!

2021-01-19 19:35 UTC, Pyr0x1 commented
Hello, sorry for the late reply, I will check it asap. Also, thanks to @Fs00 for the revision. As you may have noticed, I am not a professional translator, so I ignored some of the conventions you mentioned, thank you again for pointing them out 🙂

2021-01-19 19:47 UTC, Fs00 commented on app/src/main/res/values-it/strings.xml
> +    <string name="fling">Interruzione di Pagina</string>
Maybe "Scorrimento rapido" could be a good candidate?

2021-01-19 19:50 UTC, Pyr0x1 commented on app/src/main/res/values-it/strings.xml
> +    <string name="fling">Interruzione di Pagina</string>
I guess it could fit

2021-01-19 20:00 UTC, Pyr0x1 commented on app/src/main/res/values-it/strings.xml
> +    <string name="appChangelog">Change Log</string>
I often see the term "Changelog" even in italian localizations, that's why I left it in this way, but I agree on translating it to "Novità".

2021-01-19 20:04 UTC, Pyr0x1 commented on app/src/main/res/values-it/strings.xml
> +    <string name="scroll">Scrolling Orizzontale</string>
I often found it left as is in italian localizations, but I agree that If there is an appropriate translation it is good to use it

2021-01-21 08:23 UTC, Fs00 requested changes
There are some other things left to fix.
Also while you're at it, if you could replace tabs with spaces it would be perfect (here on GitHub everything looks unaligned).

2021-01-21 08:23 UTC, Fs00 commented on app/src/main/res/values-it/strings.xml
> +    <string name="show_in_launcher_summary">Potrebbe essere necessario riavviare il launcher perché le modifiche abbiano effetto</string>
"affinché" is much more correct than "perché" in this context.
Also, I think it's better to use "l'opzione" instead of the plural "le modifiche", the plural seems to refer to something more than just enabling/disabling that option imho

2021-01-21 08:23 UTC, Fs00 commented on app/src/main/res/values-it/strings.xml
> +    <string name="description__permission">Quest\'app necessita dei permessi di lettura nell\'archivio del telefono. Premi il pulsante per consentire l\'accesso all\'archivio del telefono, altrimenti
I've noticed it only now, I would remove the repetition of "del telefono" in the second sentence, it only makes the sentence unnecessarily wordy.

2021-01-21 08:23 UTC, Fs00 commented on app/src/main/res/values-it/strings.xml
> +	<string name="fling_summary">Effettua uno scorrimento veloce per saltare direttamente alla pagina successiva</string>
I would propose an alternative translation that is imho a bit more natural and less 1:1: "Passa direttamente alla pagina successiva con un tocco" (o "scorrimento" if you prefer) "rapido"

2021-01-30 19:26 UTC, Fs00 approved these changes

2021-02-21 13:20 UTC, merged